export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

import { useStyles } from './styles';

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				style={{
					display: 'flex',
					flexDirection: 'column',
					width: '100vw',
					height: '100vh',
					justifyContent: 'center',
					alignItems: 'center',
				}}>
				{children}
			</body>
		</html>
	);
}
